//! Document-side alias enrichment (ADR-074, T0.3.x Thread-2 Gap-2 fix).
//!
//! ## The problem this fixes (Gap 2 — vocabulary gap)
//!
//! A fact stored *without* the obvious keyword — "settled in **Porto**" (not
//! "lives in"), "raising **twins**" (not "kids") — is outranked by, or in a
//! dense-distractor field drops below, facts that carry the literal keyword.
//! Ground-truth probing of the real `seeded-vault-1k` (2026-06-09) proved the
//! killer case: the agent's keyword query `"home location city country lives
//! residence"` returned bare Porto **ABSENT** (top 0.0013, buried under
//! Salt-Lake-City distractors). The agent's keyword-soup is the *trigger*, so a
//! query-side fix would replicate the harmful soup. The fix is **document-side**.
//!
//! ## The fix (PROVEN by the `probe_enrichment` A/B)
//!
//! Enrich each fact's *embedded text* with a comprehension-generated alias /
//! topic line — `"<content> Topics: home, lives, residence, city, country,
//! location"` — generated by Phi-4 at consolidation. Measured on the hardest
//! case: bare Porto **ABSENT** → enriched Porto **rank 1 @ 0.9965** on the exact
//! killer query, with no regression on natural phrasings. Twins: rank 5 → 1.
//!
//! ## Where the alias line lives (ADR-074 §b)
//!
//! The aliases are stored in [`Memory::metadata`] under the `"enrichment"` key
//! and concatenated onto the *embedded* text only ([`compose_embed_text`]).
//! `Memory::content` — the display text the read path returns to the agent — is
//! **never** modified, so the alias line cannot leak into what the user sees.
//! The aliases are a vector-channel boost only; BM25 still indexes clean
//! `content`. The Gap-2 miss was a vector/vocabulary gap, so that is sufficient.
//!
//! ## Idempotency (ADR-074 §c)
//!
//! Each enriched fact records a [`content_fingerprint`] of the `content` the
//! aliases were generated from (`metadata.enrichment.content_fp`).
//! [`enrich_one`] returns `Ok(None)` (skip) when that fingerprint still matches
//! the current content, so the first nightly run backfills the whole vault and
//! steady-state runs only re-embed facts whose content was newly written or
//! changed (a merge / update mints fresh content → fresh fingerprint →
//! re-enrich). This bounds the per-night re-embed cost to what actually changed.
//!
//! ## Failure semantics (ADR-074, locked-next-arc Step 4)
//!
//! A per-fact LLM or embedding failure surfaces as `Err` from [`enrich_one`];
//! the orchestrator ([`crate::Consolidator::enrich_facts`]) logs-and-counts it
//! and continues — one bad fact never aborts the run, and the fact is retried
//! next cycle (its fingerprint was never written).

use crate::prompt_guard::{delimit_memory_content, guarded_system_prompt};
use serde_json::{json, Value};
use tracing::warn;
use vault_core::{Memory, VaultError, VaultResult};
use vault_embedding::EmbeddingProvider;
use vault_llm::{CompletionParams, LlmProvider};

use super::extract::{self, ExtractedGraph};

/// Metadata key the enrichment object is stored under on [`Memory::metadata`].
pub(crate) const ENRICHMENT_METADATA_KEY: &str = "enrichment";

/// JSON schema the combined enrichment call is constrained to emit. ONE call
/// returns all three products: `aliases` (the ADR-074 vocabulary boost) plus
/// `entities` + `relationships` (graph-filling, tech-debt #2). Combining them
/// keeps the per-fact LLM cost at a single call — no second pass, no worse
/// consolidator latency. GBNF-compiled in `Phi4MiniProvider`; ignored by
/// `MockLlmProvider`. The entity `type` enum mirrors `vault_core::EntityType`'s
/// snake_case names.
const ENRICHMENT_SCHEMA: &str = r#"{"type":"object","properties":{"aliases":{"type":"array","items":{"type":"string"},"minItems":1,"maxItems":8},"entities":{"type":"array","items":{"type":"object","properties":{"name":{"type":"string"},"type":{"type":"string","enum":["person","organization","project","location","concept"]}},"required":["name","type"],"additionalProperties":false},"maxItems":8},"relationships":{"type":"array","items":{"type":"object","properties":{"from":{"type":"string"},"relation":{"type":"string"},"to":{"type":"string"}},"required":["from","relation","to"],"additionalProperties":false},"maxItems":8}},"required":["aliases","entities","relationships"],"additionalProperties":false}"#;

/// System prompt for the combined enrichment call. Mirrors the JSON-only
/// framing `topics::label_one_cluster` uses for the Phi-4 cluster-naming call.
const ENRICHMENT_SYSTEM_PROMPT: &str =
    "You analyse a single memory about the user. Respond with strict JSON only.";

/// Output-token budget for the combined call. Three small arrays fit in 384;
/// verified live (the combined-extraction probe) with no truncation across
/// entity-rich facts.
const ENRICHMENT_MAX_TOKENS: u32 = 384;

/// Stable seed so enrichment is deterministic across runs for the same content
/// (mirrors `topics.rs`'s label-determinism seed). Idempotency already skips
/// re-enrichment via the fingerprint; the seed keeps a forced re-embed (changed
/// content) reproducible.
const ENRICHMENT_SEED: u32 = 0x0A11_A5E5;

/// Build the combined enrichment prompt for one memory. Tuned live (the
/// combined-extraction probe): the SINGLE-WORD keyword wording is carried over
/// verbatim from the alias-only call so search recall does not regress, and the
/// entity-type guidance keeps products / vehicles / instruments as `concept`.
fn enrichment_prompt(content: &str) -> String {
    // BRD §11.7.3: memory content is wrapped in clear delimiters. It is
    // interpolated LAST here, the position an injected instruction most
    // wants, so the boundary has to be explicit.
    let delimited = delimit_memory_content(content);
    format!(
        "A memory about the user is below. Return strict JSON with exactly three fields.\n\
         1. \"aliases\": 5 to 8 SINGLE-WORD search keywords a person might type to find \
         this fact. Cover the general CATEGORY and the TYPE of thing it is about, using \
         common generic words — e.g. for a job: work, career, employer, occupation; for a \
         pet: animal, pet, companion. Prefer generic single words over repeating specific \
         names already in the text. Lowercase.\n\
         2. \"entities\": the distinct NAMED people, organizations, places, projects, or \
         concepts. Each has a \"name\" and a \"type\". Types: person; organization (a \
         company, startup, university, school, hospital, or other institution); location \
         (a geographic place — a city, country, or address); project (something the user \
         is building or working on); concept (any other thing — a product, vehicle, \
         instrument, skill, language, subject, event, or medical condition). A car, a \
         cello, a school subject, or a named event like a marathon is a concept. A \
         university or company is an organization, NOT a location or a project. Do NOT \
         extract job titles, roles, or professions (\"senior engineer\", \"VP of \
         Engineering\", \"teacher\") as entities — they describe a person, not a separate \
         thing. ALWAYS include \"the user\" as a person. List every name you use in a \
         relationship.\n\
         3. \"relationships\": how the entities connect. Each is {{\"from\":..., \
         \"relation\":..., \"to\":...}} where BOTH \"from\" and \"to\" are names from your \
         entities list, and \"relation\" is a short snake_case verb (works_at, lives_in, \
         sibling_of, owns, drives, learning, allergic_to). Capture the user's most \
         important link (e.g. the user to their employer); ALWAYS capture the user's \
         relationship to any family member named (parent_of, sibling_of, married_to).\n\n\
         Memory:\n{delimited}"
    )
}

/// One fact ready to be written back by the orchestrator: the cloned [`Memory`]
/// with its `metadata.enrichment` set, plus the embedding of the composed
/// `content + aliases` text. The orchestrator persists both in one
/// [`vault_storage::StorageBackend::update_memory`] call (atomic metadata +
/// vector update, by id).
///
/// `pub` (not `pub(crate)`) so an out-of-crate validation harness can enrich a
/// specific fact through the real [`enrich_one`] path without running the full
/// [`crate::Consolidator::enrich_facts`] pass — see the `scale_eval`
/// `probe_real_enrichment_1k` live probe (ADR-074 validation).
#[derive(Debug)]
pub struct EnrichedFact {
    pub memory: Memory,
    pub embedding: Vec<f32>,
    /// The knowledge graph this fact implies (entities + relationships),
    /// extracted by the SAME combined LLM call that produced the aliases. The
    /// orchestrator writes it via [`super::extract::write_extracted_to_graph`]
    /// AFTER persisting the vector. Empty when the model found nothing to
    /// extract — best-effort, never blocks the (recall-critical) vector
    /// enrichment.
    pub graph: ExtractedGraph,
}

/// Compose the text that gets *embedded* for an enriched fact: the original
/// content followed by the alias/topic line. This is embedded only — it never
/// replaces `Memory::content`. Shape matches the proven `probe_enrichment`
/// fixture verbatim (`"<content> Topics: <aliases>"`).
pub(crate) fn compose_embed_text(content: &str, aliases: &str) -> String {
    format!("{content} Topics: {aliases}")
}

/// FNV-1a 64-bit fingerprint of a fact's content, hex-encoded. Used to detect
/// whether a fact's aliases are still current. FNV-1a is deterministic and
/// stable across toolchain versions (unlike `std::hash::DefaultHasher`), so a
/// fact enriched in one build is recognised as already-enriched in the next —
/// no spurious whole-vault re-embed after a Rust upgrade. Collision risk for
/// change-detection within a single vault is negligible.
pub(crate) fn content_fingerprint(content: &str) -> String {
    let mut hash: u64 = 0xcbf2_9ce4_8422_2325; // FNV offset basis
    for byte in content.as_bytes() {
        hash ^= u64::from(*byte);
        hash = hash.wrapping_mul(0x0000_0100_0000_01b3); // FNV prime
    }
    format!("{hash:016x}")
}

/// `true` when `memory` already carries an enrichment whose recorded
/// `content_fp` matches the fact's current content — i.e. nothing to do.
pub(crate) fn is_enriched_for_current_content(memory: &Memory) -> bool {
    memory
        .metadata
        .get(ENRICHMENT_METADATA_KEY)
        .and_then(|e| e.get("content_fp"))
        .and_then(Value::as_str)
        .is_some_and(|stored| stored == content_fingerprint(&memory.content))
}

/// The exact text whose embedding is `memory`'s CURRENT stored LanceDB vector.
///
/// An enriched fact's stored vector is `embed(compose_embed_text(content,
/// alias_line))` ([`enrich_one`]); a never-enriched fact's stored vector is
/// `embed(content)` (the write / merge path embeds content directly). The
/// `alias_line` is persisted verbatim under `metadata.enrichment.aliases`, so
/// re-embedding this text reproduces the stored vector EXACTLY (deterministic
/// embedder).
///
/// Used by the checkpoint recorder ([`crate::checkpoint`]) to capture a
/// pre-image's embedding faithfully — `vault-storage` cannot re-embed, so the
/// consolidator (which holds the embedder) reconstructs the vector here.
pub(crate) fn stored_embed_text(memory: &Memory) -> String {
    if is_enriched_for_current_content(memory) {
        let alias_line = memory
            .metadata
            .get(ENRICHMENT_METADATA_KEY)
            .and_then(|e| e.get("aliases"))
            .and_then(Value::as_str)
            .unwrap_or_default();
        compose_embed_text(&memory.content, alias_line)
    } else {
        memory.content.clone()
    }
}

/// Write the enrichment object onto `metadata`, preserving any existing keys.
/// If `metadata` is not a JSON object (it conventionally is — `json!({})` at
/// write time), it is replaced with a fresh object carrying only the
/// enrichment, rather than panicking or silently dropping the new data.
fn set_enrichment_metadata(metadata: &mut Value, aliases: &str, content_fp: &str) {
    let enrichment = json!({ "aliases": aliases, "content_fp": content_fp });
    match metadata.as_object_mut() {
        Some(obj) => {
            obj.insert(ENRICHMENT_METADATA_KEY.to_string(), enrichment);
        }
        None => {
            let mut obj = serde_json::Map::new();
            obj.insert(ENRICHMENT_METADATA_KEY.to_string(), enrichment);
            *metadata = Value::Object(obj);
        }
    }
}

/// The two products of one combined enrichment call: the search-alias list
/// (recall boost) and the extracted knowledge graph (graph-filling).
struct Enrichment {
    aliases: Vec<String>,
    graph: ExtractedGraph,
}

/// Parse + normalise the alias array from the combined response: trimmed,
/// lowercased, de-blanked. Factored out so the alias-quality contract stays
/// independent of the entity/relationship parse ([`super::extract`]).
fn parse_aliases(parsed: &Value) -> Vec<String> {
    parsed
        .get("aliases")
        .and_then(Value::as_array)
        .map(|arr| {
            arr.iter()
                .filter_map(Value::as_str)
                .map(|s| s.trim().to_lowercase())
                .filter(|s| !s.is_empty())
                .collect()
        })
        .unwrap_or_default()
}

/// One combined Phi-4 call per fact → aliases + extracted graph. Mirrors
/// `topics::label_one_cluster`'s single-call shape (temp 0, fixed seed).
///
/// # Errors
///
/// [`VaultError::Llm`] if the call fails, the response is not valid JSON, or it
/// yields NO usable aliases. Aliases are the recall-critical product, so an
/// empty alias list is a failed enrichment (skip-and-retry next cycle, never a
/// run abort). The extracted graph is best-effort: a fact with good aliases but
/// nothing extractable returns an empty [`ExtractedGraph`], not an error.
async fn generate_enrichment(content: &str, llm: &dyn LlmProvider) -> VaultResult<Enrichment> {
    let params = CompletionParams {
        max_tokens: ENRICHMENT_MAX_TOKENS,
        temperature: 0.0,
        top_p: 1.0,
        seed: Some(ENRICHMENT_SEED),
        system_prompt: Some(guarded_system_prompt(ENRICHMENT_SYSTEM_PROMPT)),
    };
    let raw = llm
        .complete_json(&enrichment_prompt(content), ENRICHMENT_SCHEMA, &params)
        .await
        .map_err(|e| VaultError::Llm(format!("enrichment call: {e}")))?;

    let parsed: Value = serde_json::from_str(&raw).map_err(|e| {
        warn!(raw_response = %raw, "enrichment returned malformed JSON");
        VaultError::Llm(format!(
            "enrichment response failed to parse: {e} (raw: {raw})"
        ))
    })?;

    let aliases = parse_aliases(&parsed);
    if aliases.is_empty() {
        return Err(VaultError::Llm(
            "enrichment returned no usable aliases".into(),
        ));
    }
    let graph = extract::parse_extracted(&parsed);
    Ok(Enrichment { aliases, graph })
}

/// Enrich one fact, or decide it needs no work.
///
/// - `Ok(None)` — the fact is already enriched for its current content (skip).
/// - `Ok(Some(EnrichedFact))` — a freshly enriched clone + the embedding of its
///   composed `content + aliases` text, for the orchestrator to persist via
///   `update_memory`.
/// - `Err(_)` — the LLM or embedder failed for this fact; the orchestrator
///   logs-and-counts and continues (the fact is retried next cycle, since no
///   fingerprint was written).
///
/// `content` (the display text) is never mutated — only `metadata.enrichment`
/// is added and the *embedding* carries the alias line.
///
/// `pub` so a validation harness can enrich a single fact via the real path
/// (ADR-074 `probe_real_enrichment_1k`); the orchestrator
/// [`crate::Consolidator::enrich_facts`] is the production caller.
pub async fn enrich_one(
    memory: &Memory,
    llm: &dyn LlmProvider,
    embeddings: &dyn EmbeddingProvider,
) -> VaultResult<Option<EnrichedFact>> {
    if is_enriched_for_current_content(memory) {
        return Ok(None);
    }
    let Enrichment { aliases, graph } = generate_enrichment(&memory.content, llm).await?;
    let alias_line = aliases.join(", ");
    let embed_text = compose_embed_text(&memory.content, &alias_line);
    let embedding = embeddings.embed(&embed_text).await?;

    let mut enriched = memory.clone();
    let fingerprint = content_fingerprint(&memory.content);
    set_enrichment_metadata(&mut enriched.metadata, &alias_line, &fingerprint);
    Ok(Some(EnrichedFact {
        memory: enriched,
        embedding,
        graph,
    }))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;
    use std::sync::atomic::{AtomicU64, Ordering};
    use std::sync::Arc;
    use vault_core::{Boundary, MemoryType, NewMemory};
    use vault_embedding::EMBEDDING_DIM;
    use vault_llm::MockLlmProvider;

    /// Records each embed call's text + count so tests can assert the composed
    /// `content + aliases` text is what gets embedded. Mirrors the
    /// `merge.rs::StubEmbedder` pattern.
    struct StubEmbedder {
        last_text: tokio::sync::Mutex<Option<String>>,
        call_count: AtomicU64,
    }

    impl StubEmbedder {
        fn new() -> Arc<Self> {
            Arc::new(Self {
                last_text: tokio::sync::Mutex::new(None),
                call_count: AtomicU64::new(0),
            })
        }
        async fn last(&self) -> Option<String> {
            self.last_text.lock().await.clone()
        }
        fn calls(&self) -> u64 {
            self.call_count.load(Ordering::SeqCst)
        }
    }

    #[async_trait::async_trait]
    impl EmbeddingProvider for StubEmbedder {
        async fn embed(&self, text: &str) -> VaultResult<Vec<f32>> {
            self.call_count.fetch_add(1, Ordering::SeqCst);
            *self.last_text.lock().await = Some(text.to_string());
            Ok(vec![1.0_f32 / (EMBEDDING_DIM as f32).sqrt(); EMBEDDING_DIM])
        }
    }

    fn make_memory(content: &str) -> Memory {
        Memory::try_new(NewMemory {
            content: content.into(),
            memory_type: MemoryType::Semantic,
            boundary: Boundary::new("test").unwrap(),
            source_agent: None,
            confidence: 0.9,
            valid_from: None,
            valid_until: None,
            metadata: json!({}),
        })
        .expect("valid memory")
    }

    // ─── content_fingerprint ──────────────────────────────────────────────

    #[test]
    fn content_fingerprint_is_stable_and_content_sensitive() {
        let a = content_fingerprint("settled in Porto");
        assert_eq!(a, content_fingerprint("settled in Porto"), "deterministic");
        assert_ne!(
            a,
            content_fingerprint("settled in Lisbon"),
            "different content → different fingerprint"
        );
        assert_eq!(a.len(), 16, "16 hex chars (u64)");
    }

    // ─── compose_embed_text ───────────────────────────────────────────────

    #[test]
    fn compose_embed_text_matches_probe_shape() {
        // The exact shape proven by probe_enrichment (bare Porto ABSENT →
        // rank 1). If this drifts, the proven rank-lift is no longer what we
        // ship.
        let out = compose_embed_text(
            "The user settled in Porto after years of moving around.",
            "home, lives, residence, city, country, location",
        );
        assert_eq!(
            out,
            "The user settled in Porto after years of moving around. \
             Topics: home, lives, residence, city, country, location"
        );
    }

    // ─── set_enrichment_metadata ──────────────────────────────────────────

    #[test]
    fn set_enrichment_metadata_preserves_existing_keys() {
        let mut md = json!({ "source": "agent-x", "tag": 7 });
        set_enrichment_metadata(&mut md, "home, lives", "deadbeefdeadbeef");
        assert_eq!(md.get("source").and_then(Value::as_str), Some("agent-x"));
        assert_eq!(md.get("tag").and_then(Value::as_i64), Some(7));
        let enr = md.get(ENRICHMENT_METADATA_KEY).expect("enrichment present");
        assert_eq!(
            enr.get("aliases").and_then(Value::as_str),
            Some("home, lives")
        );
        assert_eq!(
            enr.get("content_fp").and_then(Value::as_str),
            Some("deadbeefdeadbeef")
        );
    }

    #[test]
    fn set_enrichment_metadata_replaces_non_object_metadata() {
        let mut md = json!("not an object");
        set_enrichment_metadata(&mut md, "a, b", "feed");
        assert!(md.is_object());
        assert_eq!(
            md.get(ENRICHMENT_METADATA_KEY)
                .and_then(|e| e.get("aliases"))
                .and_then(Value::as_str),
            Some("a, b")
        );
    }

    // ─── is_enriched_for_current_content ──────────────────────────────────

    #[test]
    fn is_enriched_true_only_when_fingerprint_matches_current_content() {
        let mut m = make_memory("settled in Porto");
        assert!(
            !is_enriched_for_current_content(&m),
            "fresh fact: not enriched"
        );

        // Enrich for the CURRENT content → recognised as current.
        set_enrichment_metadata(
            &mut m.metadata,
            "home, lives",
            &content_fingerprint(&m.content),
        );
        assert!(is_enriched_for_current_content(&m));

        // Content changes (e.g. an update/merge) → stale fingerprint → re-enrich.
        m.content = "moved to Lisbon".into();
        assert!(
            !is_enriched_for_current_content(&m),
            "changed content must invalidate the enrichment"
        );
    }

    // ─── enrich_one ───────────────────────────────────────────────────────

    #[tokio::test]
    async fn enrich_one_composes_content_plus_aliases_and_sets_metadata() {
        let m = make_memory("The user settled in Porto after years of moving around.");
        let llm = MockLlmProvider::new(
            "mock",
            r#"{"aliases":["home","lives","residence","city","country","location"]}"#,
        );
        let embedder = StubEmbedder::new();

        let out = enrich_one(&m, &llm, embedder.as_ref())
            .await
            .expect("enrich_one ok")
            .expect("should enrich a fresh fact");

        // The embedded text is content + the alias line (probe shape).
        assert_eq!(
            embedder.last().await.as_deref(),
            Some(
                "The user settled in Porto after years of moving around. \
                 Topics: home, lives, residence, city, country, location"
            )
        );
        assert_eq!(embedder.calls(), 1);

        // Display content is untouched.
        assert_eq!(out.memory.content, m.content);

        // Metadata carries the alias line + a fingerprint of the CURRENT content.
        let enr = out
            .memory
            .metadata
            .get(ENRICHMENT_METADATA_KEY)
            .expect("enrichment metadata present");
        assert_eq!(
            enr.get("aliases").and_then(Value::as_str),
            Some("home, lives, residence, city, country, location")
        );
        assert_eq!(
            enr.get("content_fp").and_then(Value::as_str),
            Some(content_fingerprint(&m.content).as_str())
        );

        // The returned fact is now recognised as already-enriched (idempotent).
        assert!(is_enriched_for_current_content(&out.memory));
    }

    #[tokio::test]
    async fn enrich_one_skips_already_enriched_fact_without_calling_llm_or_embedder() {
        let mut m = make_memory("settled in Porto");
        set_enrichment_metadata(
            &mut m.metadata,
            "home, lives",
            &content_fingerprint(&m.content),
        );
        // A mock that would PANIC the assertion if called (call_count check).
        let llm = MockLlmProvider::new("mock", r#"{"aliases":["x"]}"#);
        let embedder = StubEmbedder::new();

        let out = enrich_one(&m, &llm, embedder.as_ref())
            .await
            .expect("enrich_one ok");
        assert!(out.is_none(), "already-enriched fact must be skipped");
        assert_eq!(embedder.calls(), 0, "no re-embed for an unchanged fact");
        assert_eq!(llm.call_count(), 0, "no LLM call for an unchanged fact");
    }

    #[tokio::test]
    async fn enrich_one_re_enriches_when_content_changed() {
        let mut m = make_memory("moved to Lisbon");
        // Enrichment recorded for DIFFERENT (old) content → stale.
        set_enrichment_metadata(
            &mut m.metadata,
            "old, aliases",
            &content_fingerprint("old text"),
        );
        let llm = MockLlmProvider::new("mock", r#"{"aliases":["home","residence"]}"#);
        let embedder = StubEmbedder::new();

        let out = enrich_one(&m, &llm, embedder.as_ref())
            .await
            .expect("enrich_one ok");
        assert!(
            out.is_some(),
            "stale fingerprint must trigger re-enrichment"
        );
        assert_eq!(embedder.calls(), 1);
    }

    #[tokio::test]
    async fn enrich_one_normalises_aliases_to_trimmed_lowercase() {
        let m = make_memory("raising twins");
        let llm = MockLlmProvider::new("mock", r#"{"aliases":["  Children ","KIDS","  "]}"#);
        let embedder = StubEmbedder::new();

        let out = enrich_one(&m, &llm, embedder.as_ref())
            .await
            .expect("ok")
            .expect("some");
        // Blank entry dropped; rest trimmed + lowercased.
        assert_eq!(
            out.memory
                .metadata
                .get(ENRICHMENT_METADATA_KEY)
                .and_then(|e| e.get("aliases"))
                .and_then(Value::as_str),
            Some("children, kids")
        );
    }

    #[tokio::test]
    async fn enrich_one_surfaces_malformed_llm_json_as_err() {
        let m = make_memory("raising twins");
        let llm = MockLlmProvider::new("mock", "not even close to JSON");
        let embedder = StubEmbedder::new();

        let err = enrich_one(&m, &llm, embedder.as_ref())
            .await
            .expect_err("malformed JSON must surface as Err");
        assert!(matches!(err, VaultError::Llm(_)), "got {err:?}");
        assert_eq!(embedder.calls(), 0, "no embed when alias generation failed");
    }

    #[tokio::test]
    async fn enrich_one_errs_on_empty_alias_list() {
        let m = make_memory("raising twins");
        let llm = MockLlmProvider::new("mock", r#"{"aliases":[]}"#);
        let embedder = StubEmbedder::new();

        let err = enrich_one(&m, &llm, embedder.as_ref())
            .await
            .expect_err("empty alias list must surface as Err (retry next cycle)");
        assert!(matches!(err, VaultError::Llm(_)), "got {err:?}");
    }

    // ─── REAL Phi-4 alias-quality probe (ADR-074 live validation) ────────────
    //
    // The mock-LLM tests above prove the *logic* (compose / store / idempotency
    // / fail-soft); `probe_enrichment` (vault-app) proves the *rank-lift* of a
    // given alias line. The one thing those don't cover is whether the REAL
    // Phi-4-mini, given a keyword-poor fact, actually produces good alternative
    // search terms. This probe loads the real GGUF and prints the aliases it
    // generates for the killer Gap-2 facts (Porto / twins / hives) plus a couple
    // of sanity facts — a human eyeballs whether they're sensible search words.
    //
    // Ignored (needs the ~2.5 GB GGUF + ~minutes of CPU inference). Run:
    //   $env:PHI4_MODEL_DIR="$env:APPDATA\com.zaaheen.app\models"
    //   cargo test -p vault-consolidator --lib real_phi4_alias_quality -- --ignored --nocapture
    #[tokio::test]
    #[ignore = "loads the real Phi-4 GGUF; set PHI4_MODEL_DIR; run with --ignored --nocapture"]
    async fn real_phi4_alias_quality() {
        use vault_llm::{Phi4MiniConfig, Phi4MiniProvider};

        let model_dir = std::env::var("PHI4_MODEL_DIR").unwrap_or_else(|_| {
            // Derived, never hardcoded. The literal that was here embedded a
            // username AND named com.shahbaz242630.memory-vault - a directory
            // deleted with the pre-Zaaheen build in session 34, so the fallback
            // pointed at nothing on the one machine it was written for.
            let appdata = std::env::var("APPDATA")
                .expect("set PHI4_MODEL_DIR, or run where APPDATA names the data directory");
            format!(r"{appdata}\com.zaaheen.app\models")
        });
        println!("\nloading Phi-4-mini from {model_dir} (model load + SHA verify)...");
        let provider = Phi4MiniProvider::new(Phi4MiniConfig::v0_2_default(model_dir.into()))
            .await
            .expect("load real Phi-4-mini");

        // The Gap-2 killers (keyword-poor) + two sanity facts that DO carry a
        // keyword (the aliases should still be sensible, not degenerate).
        let facts = [
            "The user settled in Porto after years of moving around.",
            "The user is raising twins who just started primary school.",
            "The user comes out in hives whenever they eat shellfish.",
            "The user runs ten kilometres three times a week.",
            "The user's blood type is O negative.",
        ];
        println!("\n================ REAL Phi-4 aliases ================");
        for fact in facts {
            match generate_enrichment(fact, &provider).await {
                Ok(enr) => {
                    println!("  FACT: {fact}");
                    println!(
                        "    -> embed text: {}",
                        compose_embed_text(fact, &enr.aliases.join(", "))
                    );
                }
                Err(e) => println!("  FACT: {fact}\n    -> ERROR: {e}"),
            }
        }
        println!("====================================================\n");
    }

    // ─── SPIKE: combined extraction quality (graph-filling feature) ──────────
    //
    // Question this answers BEFORE we wire any production code: can Phi-4-mini,
    // in ONE call, produce good aliases AND extract entities (people / places /
    // things) AND their relationships? If yes, the graph fills "for free" on
    // top of the alias call we already make per fact (no second per-fact LLM
    // pass → no worse latency wall). If the small model degrades when juggling
    // all three, we fall back to a separate extraction call or a local NER.
    //
    // This prints the RAW Phi-4 JSON for a human to judge: are the entities
    // real + typed correctly, are the relationships sensible, and did the
    // aliases stay as good as the alias-only probe above?
    //
    // Ignored (needs the real GGUF). Run:
    //   $env:PHI4_MODEL_DIR="$env:APPDATA\com.zaaheen.app\models"
    //   cargo test -p vault-consolidator --lib real_phi4_combined_extraction_quality -- --ignored --nocapture
    #[tokio::test]
    #[ignore = "loads the real Phi-4 GGUF; set PHI4_MODEL_DIR; run with --ignored --nocapture"]
    async fn real_phi4_combined_extraction_quality() {
        use vault_llm::{Phi4MiniConfig, Phi4MiniProvider};

        // Draft combined schema: aliases (as today) + entities (name + typed by
        // the EntityType enum) + relationships (from -> relation -> to). The
        // entity `type` enum mirrors vault_core::EntityType's snake_case names.
        const COMBINED_SCHEMA: &str = r#"{"type":"object","properties":{"aliases":{"type":"array","items":{"type":"string"},"minItems":1,"maxItems":8},"entities":{"type":"array","items":{"type":"object","properties":{"name":{"type":"string"},"type":{"type":"string","enum":["person","organization","project","location","concept"]}},"required":["name","type"],"additionalProperties":false},"maxItems":8},"relationships":{"type":"array","items":{"type":"object","properties":{"from":{"type":"string"},"relation":{"type":"string"},"to":{"type":"string"}},"required":["from","relation","to"],"additionalProperties":false},"maxItems":8}},"required":["aliases","entities","relationships"],"additionalProperties":false}"#;
        const COMBINED_SYSTEM_PROMPT: &str =
            "You analyse a single memory about the user. Respond with strict JSON only.";

        let model_dir = std::env::var("PHI4_MODEL_DIR").unwrap_or_else(|_| {
            // Derived, never hardcoded. The literal that was here embedded a
            // username AND named com.shahbaz242630.memory-vault - a directory
            // deleted with the pre-Zaaheen build in session 34, so the fallback
            // pointed at nothing on the one machine it was written for.
            let appdata = std::env::var("APPDATA")
                .expect("set PHI4_MODEL_DIR, or run where APPDATA names the data directory");
            format!(r"{appdata}\com.zaaheen.app\models")
        });
        println!("\nloading Phi-4-mini from {model_dir} (model load + SHA verify)...");
        let provider = Phi4MiniProvider::new(Phi4MiniConfig::v0_2_default(model_dir.into()))
            .await
            .expect("load real Phi-4-mini");

        // Entity/relationship-rich facts + the Gap-2 keyword-poor killers (to
        // confirm aliases stay good in the combined call).
        let facts = [
            "The user works at Acme Corp as a senior engineer.",
            "The user's sister Maria lives in Lisbon and works for a hospital.",
            "The user settled in Porto after years of moving around.",
            "The user is raising twins who just started primary school.",
            "The user drives a Tesla Model 3 and is learning to play the cello.",
            "The user comes out in hives whenever they eat shellfish.",
        ];

        let params = CompletionParams {
            max_tokens: 384,
            temperature: 0.0,
            top_p: 1.0,
            seed: Some(ENRICHMENT_SEED),
            // Guarded like production: this probe exists to observe what the
            // REAL model does on the REAL prompt, so it has to carry the same
            // §11.7.3 preamble the shipped path carries. It also keeps
            // `prompt_guard_coverage` free of exceptions.
            system_prompt: Some(guarded_system_prompt(COMBINED_SYSTEM_PROMPT)),
        };

        println!("\n============ REAL Phi-4 combined extraction ============");
        for fact in facts {
            let prompt = format!(
                "A memory about the user is below. Return strict JSON with exactly three fields.\n\
                 1. \"aliases\": 5 to 8 SINGLE-WORD search keywords a person might type to find \
                 this fact. Cover the general CATEGORY and the TYPE of thing it is about, using \
                 common generic words — e.g. for a job: work, career, employer, occupation; for a \
                 pet: animal, pet, companion. Prefer generic single words over repeating specific \
                 names already in the text. Lowercase.\n\
                 2. \"entities\": the distinct people, organizations, places, projects, or concepts \
                 named. Each has a \"name\" and a \"type\". Types: person; organization (a company \
                 or institution like a hospital or employer); location (a place); project; concept \
                 (anything else — a product, vehicle, instrument, skill, subject, or medical \
                 condition). A car, a cello, or a school subject is a concept, NOT an organization. \
                 ALWAYS include \"the user\" as a person. List every name you use in a relationship.\n\
                 3. \"relationships\": how the entities connect. Each is {{\"from\":..., \
                 \"relation\":..., \"to\":...}} where BOTH \"from\" and \"to\" are names from your \
                 entities list, and \"relation\" is a short snake_case verb (works_at, lives_in, \
                 sibling_of, owns, drives, learning, allergic_to). Capture the user's most \
                 important link (e.g. the user to their employer).\n\n\
                 Memory: {fact}"
            );
            match provider
                .complete_json(&prompt, COMBINED_SCHEMA, &params)
                .await
            {
                Ok(raw) => {
                    println!("\n  FACT: {fact}");
                    println!("  RAW : {raw}");
                }
                Err(e) => println!("\n  FACT: {fact}\n  ERROR: {e}"),
            }
        }
        println!("\n========================================================\n");
    }

    // ─── SCORED extraction-quality measurement (ADR-SEC-002 Part 2 gate) ──────
    //
    // The print-only probe above is for eyeballing; THIS measures
    // entity/relationship precision + recall against a hand-labelled corpus, so
    // the "is the graph good enough to wire into the read path?" gate is a
    // number, not a vibe. Reuses the production `generate_enrichment` path
    // (real combined schema + prompt + parse/cleanup), so it scores exactly what
    // ships.
    //
    // Relationships are scored two ways: STRICT (exact relation label) and
    // ENDPOINT (the from->to connection, any label). Endpoint is the decision
    // metric — a wrong *connection* corrupts answers; a label variant
    // (employed_at vs works_at) does not. The bar (founder-set 2026-06-27):
    // endpoint-precision >= 0.85, entity-precision >= 0.90, endpoint-recall >= 0.60.

    /// One hand-labelled fact: content + the entities `(name, type)` and
    /// relationships `(from, relation, to)` a correct extraction should produce.
    /// `the user` (person) is implied present in every fact.
    struct Labeled {
        fact: &'static str,
        entities: &'static [(&'static str, &'static str)],
        rels: &'static [(&'static str, &'static str, &'static str)],
    }

    /// The labelled corpus — representative user memories spanning all five
    /// entity types and the common relations. Ground truth is intentionally
    /// conservative (only links a careful human would call unambiguous).
    const LABELLED_CORPUS: &[Labeled] = &[
        Labeled {
            fact: "The user works at Acme Corp as a senior engineer.",
            entities: &[("the user", "person"), ("Acme Corp", "organization")],
            rels: &[("the user", "works_at", "Acme Corp")],
        },
        Labeled {
            fact: "The user's sister Maria lives in Lisbon and works for a hospital.",
            entities: &[
                ("the user", "person"),
                ("Maria", "person"),
                ("Lisbon", "location"),
                ("hospital", "organization"),
            ],
            rels: &[
                ("the user", "sibling_of", "Maria"),
                ("Maria", "lives_in", "Lisbon"),
                ("Maria", "works_at", "hospital"),
            ],
        },
        Labeled {
            fact: "The user settled in Porto after years of moving around.",
            entities: &[("the user", "person"), ("Porto", "location")],
            rels: &[("the user", "lives_in", "Porto")],
        },
        Labeled {
            fact: "The user drives a Tesla Model 3 and is learning to play the cello.",
            entities: &[
                ("the user", "person"),
                ("Tesla Model 3", "concept"),
                ("cello", "concept"),
            ],
            rels: &[
                ("the user", "drives", "Tesla Model 3"),
                ("the user", "learning", "cello"),
            ],
        },
        Labeled {
            fact: "The user comes out in hives whenever they eat shellfish.",
            entities: &[("the user", "person"), ("shellfish", "concept")],
            rels: &[("the user", "allergic_to", "shellfish")],
        },
        Labeled {
            fact: "The user married Elena last spring.",
            entities: &[("the user", "person"), ("Elena", "person")],
            rels: &[("the user", "married_to", "Elena")],
        },
        Labeled {
            fact: "The user is building a side project called Habitly, a habit tracker.",
            entities: &[("the user", "person"), ("Habitly", "project")],
            rels: &[("the user", "works_on", "Habitly")],
        },
        Labeled {
            fact: "The user studied computer science at Stanford.",
            entities: &[
                ("the user", "person"),
                ("Stanford", "organization"),
                ("computer science", "concept"),
            ],
            rels: &[("the user", "studied_at", "Stanford")],
        },
        Labeled {
            fact: "The user reports to Sarah, the VP of Engineering.",
            entities: &[("the user", "person"), ("Sarah", "person")],
            rels: &[("the user", "reports_to", "Sarah")],
        },
        Labeled {
            fact: "The user lived in Berlin before relocating to Lisbon.",
            entities: &[
                ("the user", "person"),
                ("Berlin", "location"),
                ("Lisbon", "location"),
            ],
            rels: &[
                ("the user", "lived_in", "Berlin"),
                ("the user", "lives_in", "Lisbon"),
            ],
        },
        Labeled {
            fact: "The user is allergic to penicillin.",
            entities: &[("the user", "person"), ("penicillin", "concept")],
            rels: &[("the user", "allergic_to", "penicillin")],
        },
        Labeled {
            fact: "The user co-founded a startup named Nimbus with their friend David.",
            entities: &[
                ("the user", "person"),
                ("Nimbus", "organization"),
                ("David", "person"),
            ],
            rels: &[
                ("the user", "founded", "Nimbus"),
                ("the user", "knows", "David"),
            ],
        },
        Labeled {
            fact: "The user owns a small apartment in Madrid.",
            entities: &[
                ("the user", "person"),
                ("apartment", "concept"),
                ("Madrid", "location"),
            ],
            rels: &[("the user", "owns", "apartment")],
        },
        Labeled {
            fact: "The user speaks fluent Japanese.",
            entities: &[("the user", "person"), ("Japanese", "concept")],
            rels: &[("the user", "speaks", "Japanese")],
        },
        Labeled {
            fact: "The user volunteers at the Red Cross on weekends.",
            entities: &[("the user", "person"), ("Red Cross", "organization")],
            rels: &[("the user", "volunteers_at", "Red Cross")],
        },
        Labeled {
            fact: "The user is training for the Boston Marathon.",
            entities: &[("the user", "person"), ("Boston Marathon", "concept")],
            rels: &[("the user", "training_for", "Boston Marathon")],
        },
        Labeled {
            fact: "The user manages a team of five at Globex.",
            entities: &[("the user", "person"), ("Globex", "organization")],
            rels: &[("the user", "works_at", "Globex")],
        },
        Labeled {
            fact: "The user grew up in Dublin.",
            entities: &[("the user", "person"), ("Dublin", "location")],
            rels: &[("the user", "grew_up_in", "Dublin")],
        },
        Labeled {
            fact: "The user's father Tom is a retired teacher.",
            entities: &[("the user", "person"), ("Tom", "person")],
            rels: &[("the user", "parent_of", "Tom")],
        },
        Labeled {
            fact: "The user uses Notion to organise their research.",
            entities: &[("the user", "person"), ("Notion", "concept")],
            rels: &[("the user", "uses", "Notion")],
        },
    ];

    /// Map an [`EntityType`] to the lowercase label the corpus uses.
    fn et_label(et: &vault_core::EntityType) -> String {
        use vault_core::EntityType as T;
        match et {
            T::Person => "person".into(),
            T::Organization => "organization".into(),
            T::Project => "project".into(),
            T::Location => "location".into(),
            T::Concept => "concept".into(),
            T::Custom(s) => s.to_lowercase(),
        }
    }

    /// Micro-averaged precision/recall accumulator over set-membership keys.
    #[derive(Default)]
    struct PrAccum {
        tp: usize,
        predicted: usize,
        truth: usize,
    }

    impl PrAccum {
        fn add(&mut self, predicted: &HashSet<String>, truth: &HashSet<String>) {
            self.tp += predicted.intersection(truth).count();
            self.predicted += predicted.len();
            self.truth += truth.len();
        }
        fn precision(&self) -> f64 {
            if self.predicted == 0 {
                0.0
            } else {
                self.tp as f64 / self.predicted as f64
            }
        }
        fn recall(&self) -> f64 {
            if self.truth == 0 {
                0.0
            } else {
                self.tp as f64 / self.truth as f64
            }
        }
    }

    fn nk(s: &str) -> String {
        s.trim().to_lowercase()
    }

    /// Build the (entity, strict-rel, endpoint-rel) key sets for a predicted or
    /// ground-truth graph. Pure — unit-tested below without the LLM.
    fn entity_keys(g: &ExtractedGraph) -> HashSet<String> {
        g.entities
            .iter()
            .map(|e| format!("{}|{}", nk(&e.name), et_label(&e.entity_type)))
            .collect()
    }
    fn strict_rel_keys(g: &ExtractedGraph) -> HashSet<String> {
        g.relationships
            .iter()
            .map(|r| format!("{}|{}|{}", nk(&r.from), nk(&r.relation), nk(&r.to)))
            .collect()
    }
    fn endpoint_rel_keys(g: &ExtractedGraph) -> HashSet<String> {
        g.relationships
            .iter()
            .map(|r| format!("{}|{}", nk(&r.from), nk(&r.to)))
            .collect()
    }

    fn labeled_to_graph(l: &Labeled) -> ExtractedGraph {
        ExtractedGraph {
            entities: l
                .entities
                .iter()
                .map(|(n, t)| super::extract::ExtractedEntity {
                    name: (*n).to_string(),
                    entity_type: match *t {
                        "person" => vault_core::EntityType::Person,
                        "organization" => vault_core::EntityType::Organization,
                        "project" => vault_core::EntityType::Project,
                        "location" => vault_core::EntityType::Location,
                        _ => vault_core::EntityType::Concept,
                    },
                })
                .collect(),
            relationships: l
                .rels
                .iter()
                .map(|(f, rel, t)| super::extract::ExtractedRelationship {
                    from: (*f).to_string(),
                    relation: (*rel).to_string(),
                    to: (*t).to_string(),
                })
                .collect(),
        }
    }

    /// Unit test the scorer math with NO LLM — a known predicted graph vs a
    /// known truth graph, asserting the P/R it produces.
    #[test]
    fn extraction_scorer_computes_precision_recall() {
        // Truth: 2 entities, 1 relationship (user works_at Acme).
        let truth = ExtractedGraph {
            entities: vec![
                super::extract::ExtractedEntity {
                    name: "the user".into(),
                    entity_type: vault_core::EntityType::Person,
                },
                super::extract::ExtractedEntity {
                    name: "Acme Corp".into(),
                    entity_type: vault_core::EntityType::Organization,
                },
            ],
            relationships: vec![super::extract::ExtractedRelationship {
                from: "the user".into(),
                relation: "works_at".into(),
                to: "Acme Corp".into(),
            }],
        };
        // Prediction: right entities, but the relation LABEL differs
        // (employed_at) and it adds one spurious entity.
        let pred = ExtractedGraph {
            entities: vec![
                super::extract::ExtractedEntity {
                    name: "The User".into(), // case-insensitive match
                    entity_type: vault_core::EntityType::Person,
                },
                super::extract::ExtractedEntity {
                    name: "Acme Corp".into(),
                    entity_type: vault_core::EntityType::Organization,
                },
                super::extract::ExtractedEntity {
                    name: "spurious".into(),
                    entity_type: vault_core::EntityType::Concept,
                },
            ],
            relationships: vec![super::extract::ExtractedRelationship {
                from: "the user".into(),
                relation: "employed_at".into(),
                to: "Acme Corp".into(),
            }],
        };

        let mut ent = PrAccum::default();
        ent.add(&entity_keys(&pred), &entity_keys(&truth));
        // 2 of 3 predicted entities correct → P = 2/3; both truth found → R = 1.
        assert!((ent.precision() - 2.0 / 3.0).abs() < 1e-9);
        assert!((ent.recall() - 1.0).abs() < 1e-9);

        let mut strict = PrAccum::default();
        strict.add(&strict_rel_keys(&pred), &strict_rel_keys(&truth));
        // Label differs → strict miss: P = 0, R = 0.
        assert_eq!(strict.tp, 0);

        let mut endpoint = PrAccum::default();
        endpoint.add(&endpoint_rel_keys(&pred), &endpoint_rel_keys(&truth));
        // Endpoint (user→Acme) matches regardless of label → P = 1, R = 1.
        assert!((endpoint.precision() - 1.0).abs() < 1e-9);
        assert!((endpoint.recall() - 1.0).abs() < 1e-9);
    }

    // Run:
    //   $env:PHI4_MODEL_DIR="$env:APPDATA\com.zaaheen.app\models"
    //   cargo test -p vault-consolidator --lib real_phi4_extraction_scored -- --ignored --nocapture
    #[tokio::test]
    #[ignore = "loads the real Phi-4 GGUF; set PHI4_MODEL_DIR; run with --ignored --nocapture"]
    async fn real_phi4_extraction_scored() {
        use vault_llm::{Phi4MiniConfig, Phi4MiniProvider};

        let model_dir = std::env::var("PHI4_MODEL_DIR").unwrap_or_else(|_| {
            // Derived, never hardcoded. The literal that was here embedded a
            // username AND named com.shahbaz242630.memory-vault - a directory
            // deleted with the pre-Zaaheen build in session 34, so the fallback
            // pointed at nothing on the one machine it was written for.
            let appdata = std::env::var("APPDATA")
                .expect("set PHI4_MODEL_DIR, or run where APPDATA names the data directory");
            format!(r"{appdata}\com.zaaheen.app\models")
        });
        println!("\nloading Phi-4-mini from {model_dir}...");
        let provider = Phi4MiniProvider::new(Phi4MiniConfig::v0_2_default(model_dir.into()))
            .await
            .expect("load real Phi-4-mini");

        let (mut ent, mut strict, mut endpoint) =
            (PrAccum::default(), PrAccum::default(), PrAccum::default());

        println!(
            "\n================ SCORED EXTRACTION ({} facts) ================",
            LABELLED_CORPUS.len()
        );
        for l in LABELLED_CORPUS {
            let truth = labeled_to_graph(l);
            let predicted = match generate_enrichment(l.fact, &provider).await {
                Ok(enr) => enr.graph,
                Err(e) => {
                    println!("\n  FACT: {}\n    -> ERROR: {e}", l.fact);
                    ExtractedGraph::default()
                }
            };

            let (pe, te) = (entity_keys(&predicted), entity_keys(&truth));
            let (pp, tp_) = (endpoint_rel_keys(&predicted), endpoint_rel_keys(&truth));
            ent.add(&pe, &te);
            strict.add(&strict_rel_keys(&predicted), &strict_rel_keys(&truth));
            endpoint.add(&pp, &tp_);

            println!("\n  FACT: {}", l.fact);
            println!("    entities  pred {:?}", pe);
            println!("              want {:?}", te);
            println!("    miss-ent  {:?}", te.difference(&pe).collect::<Vec<_>>());
            println!("    extra-ent {:?}", pe.difference(&te).collect::<Vec<_>>());
            println!("    rel endpoints pred {:?}", pp);
            println!("                  want {:?}", tp_);
            println!(
                "    miss-rel  {:?}",
                tp_.difference(&pp).collect::<Vec<_>>()
            );
            println!(
                "    extra-rel {:?}",
                pp.difference(&tp_).collect::<Vec<_>>()
            );
        }

        println!("\n================ SCORECARD ================");
        println!(
            "  entities     P={:.3}  R={:.3}   (tp {}/{} pred, {} truth)",
            ent.precision(),
            ent.recall(),
            ent.tp,
            ent.predicted,
            ent.truth
        );
        println!(
            "  rel strict   P={:.3}  R={:.3}",
            strict.precision(),
            strict.recall()
        );
        println!(
            "  rel endpoint P={:.3}  R={:.3}   (tp {}/{} pred, {} truth)",
            endpoint.precision(),
            endpoint.recall(),
            endpoint.tp,
            endpoint.predicted,
            endpoint.truth
        );
        println!("\n  BAR (wiring gate): entity-P>=0.90  endpoint-P>=0.85  endpoint-R>=0.60");
        let pass =
            ent.precision() >= 0.90 && endpoint.precision() >= 0.85 && endpoint.recall() >= 0.60;
        println!(
            "  RESULT: {}",
            if pass {
                "CLEARS the bar"
            } else {
                "BELOW the bar"
            }
        );
        println!("===========================================\n");

        // Conservative sanity floor — a catastrophic extraction (endpoint
        // precision below half) fails loudly even in a manual run. The wiring
        // decision itself is made by reading the scorecard above, jointly.
        assert!(
            endpoint.precision() >= 0.5,
            "endpoint precision {:.3} is catastrophically low — extraction is broken, not just imperfect",
            endpoint.precision()
        );
    }
}
